import { useRoute, Link } from "wouter";
import { Award, ArrowLeft, BadgeCheck, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function CertificatePage() {
  const [match, params] = useRoute("/certificates/:code");
  const code = params?.code || "";
  const certificate = trpc.ideaForge.certificates.view.useQuery({ code }, { enabled: Boolean(match && code.length >= 8), retry: false });
  if (certificate.isLoading) return <div className="px-5 py-24 text-center text-sm text-[#7b7c91]">Verifying certificate…</div>;
  if (certificate.error || !certificate.data?.event) return <div className="mx-auto max-w-[600px] px-5 py-24 text-center"><p className="text-sm font-semibold text-[#53546f]">Certificate not found.</p><p className="mt-2 text-xs text-[#8b8c9d]">Check the code and try again.</p><Link href="/" className="mt-4 inline-block text-xs font-bold text-[#3936b4]">Return home</Link></div>;
  const { event, certificate: record, recipientName } = certificate.data;
  return <div className="mx-auto max-w-[1020px] px-5 pb-16 pt-8 print:max-w-none print:p-0"><div className="mb-5 flex items-center justify-between print:hidden"><Link href="/profile" className="inline-flex items-center gap-2 text-xs font-semibold text-[#75768b]"><ArrowLeft className="h-3.5 w-3.5" />Back to profile</Link><Button onClick={() => window.print()} variant="outline" className="rounded-xl border-[#dddcef] text-xs"><Printer className="mr-2 h-4 w-4" />Print / Save as PDF</Button></div>
    <article className="relative mx-auto flex min-h-[600px] max-w-[900px] flex-col items-center justify-center overflow-hidden border-[10px] border-[#2926a6] bg-[#fffefa] px-7 py-12 text-center shadow-[0_22px_70px_rgba(35,34,105,.14)] sm:min-h-[660px] sm:border-[14px] sm:px-16 print:min-h-[680px] print:shadow-none"><div className="absolute inset-[10px] border border-[#ded9a6] sm:inset-[16px]" /><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-[radial-gradient(circle,rgba(229,226,255,.8),transparent_70%)]" /><div className="absolute -bottom-32 -left-24 h-96 w-96 rounded-full bg-[radial-gradient(circle,rgba(252,237,215,.75),transparent_70%)]" /><div className="relative"><span className="mx-auto grid h-16 w-16 place-items-center rounded-[22px] bg-[#2926a6] text-white shadow-lg"><Award className="h-8 w-8" /></span><p className="mt-7 text-[11px] font-bold uppercase tracking-[.28em] text-[#716cd2]">IdeaForge.io · Certificate of Achievement</p><h1 className="mt-5 font-display text-[clamp(34px,5vw,56px)] font-extrabold tracking-[-.06em] text-[#292a46]">Well built.</h1><p className="mt-3 text-sm text-[#7d7e91]">This certificate is awarded to</p><p className="mt-4 font-display text-[clamp(28px,4vw,44px)] font-extrabold tracking-[-.045em] text-[#2926a6]">{recipientName}</p><div className="mx-auto mt-5 h-px max-w-[430px] bg-gradient-to-r from-transparent via-[#d8d5a5] to-transparent" /><p className="mt-6 text-sm text-[#7d7e91]">for</p><p className="mt-2 text-lg font-bold text-[#3c3d5a]">{record.achievement}</p><p className="mt-2 text-sm text-[#77788e]">at <span className="font-bold text-[#4c4d68]">{event.title}</span></p><div className="mt-9 flex flex-wrap items-center justify-center gap-x-7 gap-y-3 text-xs text-[#808195]"><span>Issued {new Date(record.issuedAt).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })}</span><span className="hidden h-1 w-1 rounded-full bg-[#b0aec3] sm:inline-block" /><span>Reference {record.code}</span></div><div className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#eef8f2] px-3.5 py-2 text-[10px] font-bold text-[#33815f]"><BadgeCheck className="h-4 w-4" />Verified against IdeaForge records</div><p className="mt-10 max-w-[430px] text-[10px] leading-5 text-[#a2a2ae]">Awarded by the event organizer and recorded on IdeaForge.io. This certificate is printable. QR verification is not included in this MVP.</p></div></article>
    <style>{`@media print { @page { size: landscape; margin: 12mm; } header, footer { display: none !important; } body { background: white !important; } }`}</style>
  </div>;
}
