import { useMemo, useState } from "react";
import { useRoute, Link } from "wouter";
import { ArrowLeft, ArrowRight, CalendarClock, CheckCircle2, ChevronDown, MapPin, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { EventCard, type EventCardData } from "@/components/EventCard";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function EventsPage() {
  const [isDetail, params] = useRoute("/events/:id");
  const id = Number(params?.id);
  const detailInput = useMemo(() => ({ id }), [id]);
  const detailQuery = trpc.ideaForge.events.detail.useQuery(detailInput, { enabled: Boolean(isDetail && id > 0), retry: 1 });
  const [domain, setDomain] = useState("All domains");
  const [format, setFormat] = useState("All formats");
  const [status, setStatus] = useState("Open");
  const [audience, setAudience] = useState("All audiences");

  const listQuery = trpc.ideaForge.events.list.useQuery(undefined, { enabled: !isDetail, retry: 1 });
  
  // Filter locally based on the fetched data (or we could pass params to the backend, but local filtering is fast here)
  const events = (listQuery.data ?? []).filter(event => {
    if (domain !== "All domains" && event.domain !== domain) return false;
    if (format !== "All formats" && event.format !== format) return false;
    if (status === "Open" && (event.status !== "open" || new Date(event.registrationDeadline) <= new Date())) return false;
    if (status === "Closed" && (event.status === "closed" || new Date(event.registrationDeadline) > new Date())) return false;
    if (audience === "Students only" && !event.studentOnly) return false;
    return true;
  });

  if (isDetail) {
    if (detailQuery.isLoading) return <PageState text="Loading event details…" />;
    if (detailQuery.error || !detailQuery.data) return <PageState text="We couldn’t find that event. It may have been removed or the link may be out of date." />;
    return <EventDetails event={detailQuery.data} />;
  }

  return <div className="mx-auto max-w-[1440px] px-5 pb-16 pt-10 lg:px-10">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Link href="/" className="mb-4 inline-flex items-center gap-2 text-xs font-semibold text-[#77788e] hover:text-[#3431ac]"><ArrowLeft className="h-3.5 w-3.5" />Home</Link><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#7773da] dark:text-[#8e8aff]">IdeaForge catalogue</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.05em] text-[#21223e] dark:text-[#f1f1fa] sm:text-[40px]">Explore events.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#77788e]">Browse organizer-published opportunities, or use AI discovery to match events to your goals.</p></div><Link href="/forge" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#2926a6] px-5 text-sm font-bold text-white shadow-[0_7px_20px_rgba(41,38,166,.16)] hover:bg-[#201d8e]">Find my match <ArrowRight className="h-4 w-4" /></Link></div>
    <div className="mt-7 flex flex-col gap-3 rounded-[20px] border border-[#e9e9f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-bold text-[#3f405d]">{listQuery.isLoading ? "Loading events…" : `${events.length} ${events.length === 1 ? "event" : "events"}`}</p><div className="flex flex-wrap gap-2">
      
      <label className="relative"><span className="sr-only">Filter by status</span><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 appearance-none rounded-xl border border-[#e8e8f0] bg-[#fbfbfe] py-2 pl-3 pr-9 text-xs font-semibold text-[#5c5d75] outline-none focus:border-[#b5b1f5]"><option>All statuses</option><option>Open</option><option>Closed</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[#9899a9]" /></label>
      
      <label className="relative"><span className="sr-only">Filter by audience</span><select value={audience} onChange={e => setAudience(e.target.value)} className="h-10 appearance-none rounded-xl border border-[#e8e8f0] bg-[#fbfbfe] py-2 pl-3 pr-9 text-xs font-semibold text-[#5c5d75] outline-none focus:border-[#b5b1f5]"><option>All audiences</option><option>Students only</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[#9899a9]" /></label>
      
      <label className="relative"><span className="sr-only">Filter by domain</span><select value={domain} onChange={e => setDomain(e.target.value)} className="h-10 appearance-none rounded-xl border border-[#e8e8f0] bg-[#fbfbfe] py-2 pl-3 pr-9 text-xs font-semibold text-[#5c5d75] outline-none focus:border-[#b5b1f5]"><option>All domains</option>{Array.from(new Set((listQuery.data ?? []).map(event => event.domain))).sort().map(value => <option key={value}>{value}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[#9899a9]" /></label>
      
      <label className="relative"><span className="sr-only">Filter by format</span><select value={format} onChange={e => setFormat(e.target.value)} className="h-10 appearance-none rounded-xl border border-[#e8e8f0] bg-[#fbfbfe] py-2 pl-3 pr-9 text-xs font-semibold text-[#5c5d75] outline-none focus:border-[#b5b1f5]"><option>All formats</option><option value="online">Online</option><option value="in-person">In person</option><option value="hybrid">Hybrid</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[#9899a9]" /></label>
      
    </div></div>
    {listQuery.isLoading ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(value => <div key={value} className="h-64 animate-pulse rounded-[22px] bg-[#ececf4]" />)}</div> : listQuery.error ? <div className="mt-6 rounded-2xl border border-[#f0dfe1] bg-white dark:bg-[#1e1e36] p-8 text-sm text-[#965b62]">Events couldn’t be loaded. Please try again.</div> : events.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map(event => <EventCard key={event.id} event={event} />)}</div> : <div className="mt-6 rounded-[22px] border border-dashed border-[#dedeeb] bg-white dark:bg-[#1e1e36] px-5 py-14 text-center"><p className="text-sm font-bold text-[#383953]">No events match those filters</p><p className="mt-1 text-xs text-[#828399]">Try another format or clear the filters.</p><Button onClick={() => { setDomain("All domains"); setFormat("All formats"); setStatus("All statuses"); setAudience("All audiences"); }} variant="outline" className="mt-4 rounded-lg">Clear filters</Button></div>}
    <div className="mt-8 rounded-[22px] border border-[#e9e8f6] bg-[#f1f0ff] dark:bg-[#2c2b53] p-5 sm:flex sm:items-center sm:justify-between"><p className="text-sm font-bold text-[#38365f]">Not sure where to start?</p><p className="mt-1 text-xs text-[#777793] sm:mt-0">Tell IdeaForge what you want to build and let it narrow the field.</p><Link href="/forge" className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#3935b6] sm:mt-0">Ask IdeaForge <ArrowRight className="h-3.5 w-3.5" /></Link></div>
  </div>;
}

type EventDetailData = EventCardData & { description: string; eligibilityText: string; studentOnly: boolean; allowedRegions: string[] | null; minGraduationYear: number | null; maxGraduationYear: number | null; resultsLocked: boolean; resultsPublished: boolean; status: "draft" | "open" | "closed"; participantCount: number; rounds: Array<{ id: number; name: string; requirements: string; dueAt: Date; sequence: number }> };

function EventDetails({ event }: { event: EventDetailData }) {
  const { isAuthenticated } = useAuth();
  const [teamSize, setTeamSize] = useState(event.minTeamSize);
  const published = trpc.ideaForge.judging.publishedResults.useQuery({ eventId: event.id }, { enabled: event.resultsPublished && isAuthenticated, retry: false });
  const registration = trpc.ideaForge.registration.register.useMutation({ onSuccess: result => toast.success(result.alreadyRegistered ? "You’re already registered for this event." : "Registration confirmed. You’re on the participant list.") , onError: error => toast.error(error.message) });
  const register = () => isAuthenticated ? registration.mutate({ eventId: event.id, teamSize }) : startLogin();
  return <div className="mx-auto max-w-[1100px] px-5 pb-16 pt-8 lg:px-10">
    <Link href="/events" className="inline-flex items-center gap-2 text-xs font-semibold text-[#73748b] hover:text-[#3431ac]"><ArrowLeft className="h-3.5 w-3.5" />Back to events</Link>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
      <div><span className="inline-flex rounded-full bg-[#f0efff] dark:bg-[#2c2b53] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.1em] text-[#514dc3]">{event.domain}</span><h1 className="mt-4 font-display text-3xl font-extrabold leading-tight tracking-[-.05em] text-[#20213d] sm:text-[44px]">{event.title}</h1><p className="mt-3 text-lg leading-7 text-[#71728a]">{event.tagline}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info icon={CalendarClock} label="Registration closes" value={new Date(event.registrationDeadline).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })} /><Info icon={MapPin} label="Format" value={event.format === "online" ? "Online" : event.location || event.format} /><Info icon={Users} label="Team size" value={`${event.minTeamSize}–${event.maxTeamSize} builders`} /></div>
        <section className="mt-8 rounded-[22px] border border-[#e9e9f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-6"><h2 className="font-display text-lg font-extrabold tracking-[-.03em] text-[#2e2f4c]">About the challenge</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-[#6f7086]">{event.description}</p><h3 className="mt-7 text-sm font-bold text-[#363752]">What you’ll need</h3><div className="mt-3 flex flex-wrap gap-2">{event.skillsRequired.map(skill => <span key={skill} className="rounded-full border border-[#ebebf2] dark:border-[#35354f] bg-[#fafafd] dark:bg-[#292943] px-3 py-1.5 text-xs font-semibold text-[#65667e]">{skill}</span>)}</div><h3 className="mt-7 text-sm font-bold text-[#363752]">Eligibility</h3><p className="mt-2 text-sm leading-6 text-[#707187]">{event.eligibilityText}</p><ul className="mt-3 space-y-1.5 text-xs text-[#707187]">{event.studentOnly && <li>• Currently enrolled students (save a program in your profile)</li>}{event.allowedRegions?.length ? <li>• Regions: {event.allowedRegions.join(", ")}</li> : null}{event.minGraduationYear || event.maxGraduationYear ? <li>• Graduation year: {event.minGraduationYear || "any"}–{event.maxGraduationYear || "any"}</li> : null}{!event.studentOnly && !event.allowedRegions?.length && !event.minGraduationYear && !event.maxGraduationYear && <li>• No structured student, region, or graduation-year restrictions listed.</li>}</ul><div className="mt-3 flex gap-2 rounded-xl bg-[#f1f8f4] p-3 text-xs leading-5 text-[#43795f]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" />Open status, deadline, team size, student-profile, region, and graduation-year rules are checked deterministically. Confirm remaining free-text conditions with the organizer.</div>
          <h3 className="mt-7 text-sm font-bold text-[#363752]">Timeline</h3><div className="mt-3 space-y-3">{event.rounds.length ? event.rounds.map((round, index) => <div key={round.id} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#f0efff] dark:bg-[#2c2b53] text-[11px] font-bold text-[#514dc3]">{index + 1}</span><div className="flex-1 border-b border-[#f0f0f5] pb-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold text-[#383953]">{round.name}</p><p className="text-xs text-[#87889c]">{new Date(round.dueAt).toLocaleDateString()}</p></div><p className="mt-1 text-xs leading-5 text-[#797a8e]">{round.requirements}</p></div></div>) : <p className="text-xs text-[#8b8ca0]">No rounds have been published yet.</p>}</div>
          {event.resultsPublished && <div className="mt-8 border-t border-[#f0f0f5] pt-6"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-[#363752]">Published results</h3><span className="rounded-full bg-[#eaf7f1] dark:bg-[#1e3d2f] px-2.5 py-1 text-[10px] font-bold text-[#32805f]">Organizer released</span></div>{!isAuthenticated ? <p className="mt-2 text-xs leading-5 text-[#7d7e91]">Sign in to view the published results.</p> : published.isLoading ? <p className="mt-3 text-xs text-[#8a8b9e] dark:text-[#74758d]">Loading results…</p> : published.error ? <p className="mt-3 text-xs text-[#986a6f]">{published.error.message}</p> : <div className="mt-3 divide-y divide-[#f0f0f5] rounded-xl border border-[#ececf3]">{(published.data?.results ?? []).map((result, index) => <div key={result.submission.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#f0efff] dark:bg-[#2c2b53] text-[10px] font-extrabold text-[#514dc3]">{index + 1}</span><div className="min-w-0"><p className="truncate text-xs font-bold text-[#44455f]">{result.submission.title}</p><p className="mt-0.5 text-[10px] text-[#8a8b9e] dark:text-[#74758d]">Team #{result.submission.teamId}</p></div></div><div className="shrink-0 text-right"><p className="text-xs font-extrabold text-[#3936b2]">{result.normalizedScore ?? "—"}<span className="font-normal text-[#9798a8] dark:text-[#74758d]"> / 100</span></p><p className="text-[9px] text-[#88899d] dark:text-[#8888a3]">raw mean {result.averageScore ?? "—"} · {result.evaluationCount} reviews</p></div></div>)}</div>}</div>}
        </section>
      </div>
      <aside className="h-fit rounded-[22px] border border-[#e7e7f0] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5 shadow-[0_9px_30px_rgba(35,35,80,.05)] lg:sticky lg:top-24"><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[#7374a0]">Registration</span><span className="rounded-full bg-[#eaf7f1] dark:bg-[#1e3d2f] px-2.5 py-1 text-[10px] font-bold capitalize text-[#29835d]">{event.status}</span></div><p className="mt-4 font-display text-2xl font-extrabold tracking-[-.04em] text-[#2b2c49] dark:text-[#f1f1fa]">{event.entryType === "free" ? "Free to enter" : "Entry fee applies"}</p><p className="mt-2 text-xs leading-5 text-[#818297]">Begins {new Date(event.startsAt).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })}. Open status and the registration deadline are checked again when you register.</p><label className="mt-5 block text-xs font-bold text-[#494a65]">Planned team size<select value={teamSize} onChange={e => setTeamSize(Number(e.target.value))} className="mt-2 block h-11 w-full rounded-xl border border-[#e7e7f0] dark:border-[#35354f] bg-[#fbfbfd] px-3 text-sm font-semibold outline-none focus:border-[#aca9ef]">{Array.from({ length: event.maxTeamSize - event.minTeamSize + 1 }, (_, i) => event.minTeamSize + i).map(size => <option value={size} key={size}>{size} {size === 1 ? "person" : "people"}</option>)}</select></label><Button onClick={register} disabled={registration.isPending} className="mt-4 h-11 w-full rounded-xl bg-[#2926a6] font-bold text-white hover:bg-[#201d8e]">{registration.isPending ? "Registering…" : "Register for this event"} <ArrowRight className="ml-2 h-4 w-4" /></Button><p className="mt-3 text-center text-[10px] leading-4 text-[#9899a8]">Registration is only recorded after server-side eligibility validation.</p><div className="mt-5 flex items-center justify-between border-t border-[#f0f0f5] pt-4 text-xs"><span className="text-[#7f8092]">Registered participants</span><span className="font-bold text-[#44455f]">{event.participantCount}</span></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-[#7f8092]">Team size</span><span className="font-bold text-[#44455f]">{event.minTeamSize}–{event.maxTeamSize}</span></div><div className="mt-4 rounded-xl bg-[#f6f6fb] p-3 text-[11px] leading-5 text-[#77788c] dark:text-[#8888a3]">Want to refine your options? <Link href="/forge" className="font-bold text-[#4340b7]">Ask IdeaForge AI</Link></div></aside>
    </div>
    <div className="mt-6 flex items-start gap-2 rounded-xl bg-[#f6f6fb] p-4 text-xs leading-5 text-[#828397]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#65a686]" />Event facts shown here come from the stored organizer record. Registration is subject to the published eligibility text and final organizer rules.</div>
  </div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof CalendarClock; label: string; value: string }) { return <div className="rounded-[16px] border border-[#eaeaf2] bg-white dark:bg-[#1e1e36] p-4"><Icon className="h-4 w-4 text-[#7974d8]" /><p className="mt-3 text-[10px] font-bold uppercase tracking-[.1em] text-[#9697a8]">{label}</p><p className="mt-1 text-xs font-bold text-[#4a4b66]">{value}</p></div>; }
function PageState({ text }: { text: string }) { return <div className="mx-auto max-w-[1000px] px-5 py-20 text-center"><p className="text-sm text-[#77788e]">{text}</p><Link href="/events" className="mt-4 inline-block text-sm font-bold text-[#3734ae]">Browse open events</Link></div>; }
