import { useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardList, Gavel, ShieldAlert, Sparkles, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function JudgePage() {
  const { user, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const assignments = trpc.ideaForge.judging.assignments.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const [scores, setScores] = useState<Record<number, string>>({});
  const [feedback, setFeedback] = useState<Record<number, string>>({});
    const conflict = trpc.ideaForge.judging.declareConflict.useMutation({ onSuccess: async () => { toast.success("Conflict declared. This assignment can no longer be scored from your account."); await utils.ideaForge.judging.assignments.invalidate(); }, onError: error => toast.error(error.message) });
  const evaluate = trpc.ideaForge.judging.evaluate.useMutation({ onSuccess: async () => { toast.success("Evaluation saved."); await utils.ideaForge.judging.assignments.invalidate(); }, onError: error => toast.error(error.message) });
  if (!isAuthenticated) return <div className="mx-auto max-w-[600px] px-5 py-24 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f0efff] dark:bg-[#2c2b53] text-[#514dc4] dark:text-[#8e8aff]"><Gavel className="h-6 w-6" /></span><h1 className="mt-5 font-display text-2xl font-extrabold text-[#292a47] dark:text-[#f1f1fa]">Judge workspace</h1><p className="mt-2 text-sm leading-6 text-[#7b7c91] dark:text-[#8888a3]">Sign in to review assigned submissions, declare conflicts, and submit rubric scores.</p><Button onClick={() => startLogin()} className="mt-5 rounded-xl bg-[#2926a6] text-white">Sign in to continue <ArrowRight className="ml-2 h-4 w-4" /></Button></div>;
  const rows = assignments.data ?? [];
  return <div className="mx-auto max-w-[1200px] px-5 pb-16 pt-9 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#7773da] dark:text-[#8e8aff]">Judge workspace</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.05em] text-[#21223e] dark:text-[#f1f1fa] sm:text-[40px]">Review the work. Elevate the ideas.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#797a8f] dark:text-[#8888a3]">Only submissions assigned to your account appear here. Scores and feedback are stored as evaluation records.</p></div><div className="rounded-xl border border-[#e9e9f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] px-4 py-3 text-xs text-[#77788d]">Your judge account ID: <b className="text-[#41425e] dark:text-[#e5e5f1]">#{user?.id}</b></div></div>
    <div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4">{assignments.isLoading ? <div className="h-48 animate-pulse rounded-[22px] bg-[#ececf4]" /> : assignments.error ? <div className="rounded-[22px] border border-[#f1dddd] bg-white dark:bg-[#1e1e36] p-7 text-sm text-[#965b62]">{assignments.error.message}</div> : rows.length === 0 ? <div className="rounded-[22px] border border-dashed border-[#dedeee] bg-white dark:bg-[#1e1e36] px-5 py-14 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#f2f1ff] text-[#5a55ce]"><ClipboardList className="h-5 w-5" /></span><h2 className="mt-4 text-sm font-extrabold text-[#42435f]">No assignments yet</h2><p className="mx-auto mt-1 max-w-[380px] text-xs leading-5 text-[#88899d] dark:text-[#8888a3]">Ask the event organizer to assign a submission to your account ID. If you haven’t enrolled as a judge yet, use the button on this page.</p></div> : rows.map(({ assignment, submission, event }) => <article key={assignment.id} className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5 shadow-[0_8px_26px_rgba(32,33,74,.04)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-[#f0efff] dark:bg-[#2c2b53] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-[#514dc3]">{event.domain}</span><h2 className="mt-3 font-display text-xl font-extrabold tracking-[-.035em] text-[#2c2d4a]">{submission.title}</h2><p className="mt-1 text-xs font-semibold text-[#71728b] dark:text-[#a3a3bb]">{event.title} · submission #{submission.id} · version {submission.version}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${assignment.conflictDeclared ? "bg-[#fff1ed] text-[#b6574e]" : "bg-[#eef8f2] text-[#2d855f]"}`}>{assignment.conflictDeclared ? "Conflict declared" : "Assigned to you"}</span></div><div className="mt-4 rounded-xl bg-[#fafafd] dark:bg-[#292943] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#85869a] dark:text-[#8888a3]">Project summary</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#5e5f78]">{submission.summary}</p><div className="mt-3 flex flex-wrap gap-3 text-xs">{submission.repositoryUrl && <a href={submission.repositoryUrl} rel="noreferrer" target="_blank" className="font-semibold text-[#4b47bd] underline underline-offset-2">Repository ↗</a>}{submission.demoUrl && <a href={submission.demoUrl} rel="noreferrer" target="_blank" className="font-semibold text-[#4b47bd] underline underline-offset-2">Demo ↗</a>}{!submission.repositoryUrl && !submission.demoUrl && <span className="text-[#9394a5] dark:text-[#74758d]">No project links included.</span>}</div></div>
        <div className="mt-5 grid gap-3 md:grid-cols-[160px_1fr]"><label className="text-xs font-bold text-[#555671]">Overall score (0–100)<input type="number" value={scores[assignment.id] ?? ""} onChange={e => setScores(previous => ({ ...previous, [assignment.id]: e.target.value }))} min="0" max="100" className="mt-2 h-10 w-full rounded-lg border border-[#e7e7ef] bg-white dark:bg-[#1e1e36] px-3 text-sm outline-none focus:border-[#aaa6ee]" /></label><label className="text-xs font-bold text-[#555671]">Feedback<textarea value={feedback[assignment.id] ?? ""} onChange={e => setFeedback(previous => ({ ...previous, [assignment.id]: e.target.value }))} minLength={10} maxLength={3000} rows={2} placeholder="Strengths, areas to improve, and rationale for your score…" className="mt-2 w-full rounded-lg border border-[#e7e7ef] bg-white dark:bg-[#1e1e36] p-3 text-xs font-normal leading-5 outline-none focus:border-[#aaa6ee]" /></label></div>
        <div className="mt-4 flex flex-wrap gap-2">{assignment.conflictDeclared ? <p className="flex items-center gap-2 rounded-lg bg-[#fff4f1] px-3 py-2 text-xs text-[#a85c52]"><ShieldAlert className="h-4 w-4" />This assignment is excluded from scoring.</p> : <><Button onClick={() => evaluate.mutate({ assignmentId: assignment.id, score: Number(scores[assignment.id]), feedback: (feedback[assignment.id] || "").trim() })} disabled={evaluate.isPending || scores[assignment.id] === undefined || !feedback[assignment.id]?.trim()} className="rounded-lg bg-[#2926a6] text-white px-4 text-xs font-bold">{evaluate.isPending ? "Saving…" : "Submit evaluation"}<CheckCircle2 className="ml-2 h-4 w-4" /></Button><Button onClick={() => { if (window.confirm("Declare a conflict for this assignment? You will not be able to score it.")) conflict.mutate({ assignmentId: assignment.id }); }} disabled={conflict.isPending} variant="outline" className="rounded-lg border-[#efd8d4] text-xs text-[#a75e53]">Declare conflict <ShieldAlert className="ml-2 h-3.5 w-3.5" /></Button></>}</div>
      </article>)}</div>
<aside className="space-y-4"><div className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0efff] dark:bg-[#2c2b53] text-[#514dc4] dark:text-[#8e8aff]"><UserRoundCheck className="h-4 w-4" /></span><h2 className="text-sm font-extrabold text-[#3a3b56] dark:text-[#f1f1fa]">Judge access</h2></div><p className="mt-3 text-xs leading-5 text-[#7c7d91] dark:text-[#8888a3]">You are officially registered as a Judge. Share your registered email with an event organizer so they can assign submissions to you.</p><div className="mt-4 rounded-lg bg-[#f9f9fb] dark:bg-[#20213d] p-3 text-center text-[11px] font-bold text-[#5a55ce] dark:text-[#8e8aff]">{user?.email || "No email linked"}</div></div>
        <div className="rounded-[22px] border border-[#e8e7f4] dark:border-[#35354f] bg-[#f1f0ff] dark:bg-[#2c2b53] p-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#5651ca]" /><h3 className="text-xs font-bold text-[#47448c]">Evaluation guidance</h3></div><ul className="mt-3 space-y-2 text-[11px] leading-5 text-[#75759b]"><li>• Ground scores in the event’s published criteria.</li><li>• Declare a conflict if you have a personal or professional connection.</li><li>• Your score and written feedback are saved together.</li><li>• Conflict-declared assignments are excluded from aggregate results.</li></ul></div>
        <div className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5"><p className="text-xs font-bold text-[#484963]">Assigned reviews</p><p className="mt-2 font-display text-3xl font-extrabold tracking-[-.05em] text-[#2c2d49]">{rows.length}</p><p className="mt-1 text-[10px] text-[#8c8d9e]">Assignments linked to your account</p></div>
      </aside>
    </div></div>;
}
