import { useEffect, useState } from "react";
import { ArrowRight, Award, BookOpenCheck, Check, ClipboardList, FileText, Link2, Plus, Save, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

const splitTags = (value: string) => value.split(",").map(item => item.trim()).filter(Boolean).slice(0, 30);
export default function ProfilePage() {
  const { user, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const profileQuery = trpc.ideaForge.profile.get.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const registrationQuery = trpc.ideaForge.registration.mine.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const teamQuery = trpc.ideaForge.teams.mine.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const submissionQuery = trpc.ideaForge.submissions.mine.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const certificateQuery = trpc.ideaForge.certificates.mine.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const eventsQuery = trpc.ideaForge.events.list.useQuery(undefined, { retry: 1 });
  const [program, setProgram] = useState("");
  const [year, setYear] = useState("");
  const [location, setLocation] = useState("");
  const [skills, setSkills] = useState("");
  const [interests, setInterests] = useState("");
  const [teamName, setTeamName] = useState("");
  const [selectedEvent, setSelectedEvent] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [joinCode, setJoinCode] = useState("");
  const [submissionTitle, setSubmissionTitle] = useState("");
  const [submissionSummary, setSubmissionSummary] = useState("");
  const [repo, setRepo] = useState("");
  const [demoUrl, setDemoUrl] = useState("");
  useEffect(() => {
    if (profileQuery.data) {
      setProgram(profileQuery.data.program || ""); setYear(profileQuery.data.graduationYear ? String(profileQuery.data.graduationYear) : ""); setLocation(profileQuery.data.location || ""); setSkills((profileQuery.data.skills || []).join(", ")); setInterests((profileQuery.data.interests || []).join(", "));
    }
  }, [profileQuery.data]);
  const save = trpc.ideaForge.profile.save.useMutation({ onSuccess: async () => { toast.success("Profile saved. Recommendations can now use these details."); await utils.ideaForge.profile.get.invalidate(); }, onError: error => toast.error(error.message) });
  const createTeam = trpc.ideaForge.teams.create.useMutation({ onSuccess: async result => { toast.success(`Team created. Invite code: ${result.inviteCode}`); setInviteCode(result.inviteCode); setTeamName(""); await utils.ideaForge.teams.mine.invalidate(); await utils.ideaForge.registration.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const joinTeam = trpc.ideaForge.teams.join.useMutation({ onSuccess: async result => { toast.success(`Joined ${result.teamName}.`); setJoinCode(""); await utils.ideaForge.teams.mine.invalidate(); await utils.ideaForge.registration.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const submit = trpc.ideaForge.submissions.submit.useMutation({ onSuccess: async result => { toast.success(`Submission version ${result.version} saved.`); setSubmissionTitle(""); setSubmissionSummary(""); await utils.ideaForge.submissions.mine.invalidate(); }, onError: error => toast.error(error.message) });
  const events = eventsQuery.data ?? [];
  const teams = teamQuery.data ?? [];
  if (!isAuthenticated) return <div className="mx-auto max-w-[600px] px-5 py-24 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f0efff] dark:bg-[#2c2b53] text-[#4d49c7]"><BookOpenCheck className="h-6 w-6" /></span><h1 className="mt-5 font-display text-2xl font-extrabold text-[#282944]">Your builder profile</h1><p className="mt-2 text-sm leading-6 text-[#7f8095]">Sign in to save your skills, track event registrations, form a team, and build your achievement record.</p><Button onClick={() => startLogin()} className="mt-5 rounded-xl bg-[#2926a6] px-5">Sign in to continue <ArrowRight className="ml-2 h-4 w-4" /></Button></div>;
  return <div className="mx-auto max-w-[1200px] px-5 pb-16 pt-9 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#7773da] dark:text-[#8e8aff]">Student space</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.05em] text-[#21223e] dark:text-[#f1f1fa]">Your builder profile.</h1><p className="mt-2 text-sm text-[#797a8f] dark:text-[#8888a3]">{user?.name || "Welcome"} · your skills, teams, and milestones in one place.</p><p className="mt-1 text-[11px] text-[#9293a4]">Account ID: <b>#{user?.id}</b> · share this with an organizer if you need judge assignments.</p></div><div className="rounded-xl border border-[#e9e9f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] px-4 py-3 text-xs text-[#797a8f] dark:text-[#8888a3]"><span className="font-bold text-[#454660] dark:text-[#e5e5f1]">Role:</span> {user?.role === "user" ? "Student" : user?.role}</div></div>
    <div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1fr)_350px]"><div className="space-y-5">
      <section className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#7a75db]">Profile details</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#2b2c49] dark:text-[#f1f1fa]">Make your matches personal</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f0efff] dark:bg-[#2c2b53] text-[#5550ca]"><UsersRound className="h-5 w-5" /></span></div>
        {profileQuery.isLoading ? <div className="mt-5 h-32 animate-pulse rounded-xl bg-[#f0f0f6]" /> : <form onSubmit={e => { e.preventDefault(); save.mutate({ program: program.trim() || undefined, graduationYear: year ? Number(year) : undefined, location: location.trim() || undefined, skills: splitTags(skills), interests: splitTags(interests) }); }} className="mt-5 grid gap-4 sm:grid-cols-2">
          <Field label="Program or department"><input value={program} onChange={e => setProgram(e.target.value)} placeholder="AI & Data Science" maxLength={180} /></Field>
          <Field label="Graduation year"><input value={year} onChange={e => setYear(e.target.value)} type="number" min="2020" max="2040" placeholder="2027" /></Field>
          <Field label="Location"><input value={location} onChange={e => setLocation(e.target.value)} placeholder="City or region" maxLength={180} /></Field>
          <div className="hidden sm:block" />
          <Field label="Skills · comma separated" wide><textarea rows={3} value={skills} onChange={e => setSkills(e.target.value)} placeholder="Python, machine learning, computer vision" maxLength={1200} /></Field>
          <Field label="Interests · comma separated" wide><textarea rows={2} value={interests} onChange={e => setInterests(e.target.value)} placeholder="Healthcare, education, accessibility" maxLength={800} /></Field>
          <div className="sm:col-span-2"><Button type="submit" disabled={save.isPending} className="rounded-xl bg-[#2926a6] px-5 font-bold"><Save className="mr-2 h-4 w-4" />{save.isPending ? "Saving…" : "Save profile"}</Button><span className="ml-3 text-[11px] text-[#9394a6]">Profile data is used to personalize discovery.</span></div>
        </form>}
      </section>
      <section className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5 sm:p-7"><SectionTitle icon={UsersRound} title="Team management" subtitle="Create or join a team after registering for an event." />
        <div className="mt-5 grid gap-4 md:grid-cols-2"><form onSubmit={e => { e.preventDefault(); if (selectedEvent) createTeam.mutate({ eventId: Number(selectedEvent), name: teamName.trim() }); }} className="rounded-2xl bg-[#fafafd] dark:bg-[#292943] p-4"><p className="text-xs font-bold text-[#454660] dark:text-[#e5e5f1]">Create a team</p><select required value={selectedEvent} onChange={e => setSelectedEvent(e.target.value)} className="mt-3 h-10 w-full rounded-lg border border-[#e6e6ef] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] px-3 text-xs outline-none focus:border-[#aaa6ee]"><option value="">Choose an event</option>{events.filter(event => registrationQuery.data?.some(reg => reg.eventId === event.id)).map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select><input required value={teamName} onChange={e => setTeamName(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#e6e6ef] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] px-3 text-xs outline-none focus:border-[#aaa6ee]" placeholder="Team name" maxLength={180} /><Button disabled={!selectedEvent || createTeam.isPending} className="mt-3 h-9 rounded-lg bg-[#2926a6] px-3 text-xs">{createTeam.isPending ? "Creating…" : "Create team"}<Plus className="ml-1.5 h-3.5 w-3.5" /></Button>{inviteCode && <p className="mt-2 break-all text-[11px] text-[#31805e]">Invite code: <b>{inviteCode}</b></p>}</form>
          <form onSubmit={e => { e.preventDefault(); joinTeam.mutate({ inviteCode: joinCode.trim() }); }} className="rounded-2xl bg-[#fafafd] dark:bg-[#292943] p-4"><p className="text-xs font-bold text-[#454660] dark:text-[#e5e5f1]">Join with an invite code</p><p className="mt-1 text-[11px] leading-5 text-[#898a9c]">The event’s team-size limit is checked before you join.</p><input required value={joinCode} onChange={e => setJoinCode(e.target.value)} className="mt-3 h-10 w-full rounded-lg border border-[#e6e6ef] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] px-3 text-xs uppercase outline-none focus:border-[#aaa6ee]" placeholder="e.g. 3C7A91B2" maxLength={32} /><Button variant="outline" disabled={joinTeam.isPending} className="mt-3 h-9 rounded-lg border-[#deddf2] px-3 text-xs text-[#413eb6]">{joinTeam.isPending ? "Joining…" : "Join team"}<ArrowRight className="ml-1.5 h-3.5 w-3.5" /></Button></form>
        </div>
        {teams.length > 0 && <div className="mt-4 space-y-2">{teams.map(team => <div key={team.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#ededf4] dark:border-[#35354f] px-4 py-3"><div><p className="text-sm font-bold text-[#3d3e59]">{team.name}</p><p className="mt-0.5 text-[11px] text-[#88899c]">Team invite code: {team.inviteCode}</p></div><span className="rounded-full bg-[#f0efff] dark:bg-[#2c2b53] px-2.5 py-1 text-[10px] font-bold text-[#514dc3]">Event #{team.eventId}</span></div>)}</div>}
      </section>
      <section className="rounded-[22px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5 sm:p-7"><SectionTitle icon={FileText} title="Project submissions" subtitle="Every resubmission creates a new version; earlier versions remain on record." />
        <form onSubmit={e => { e.preventDefault(); const team = teams.find(item => String(item.eventId) === selectedEvent); if (!selectedEvent || !team) { toast.error("Select an event where you already have a team."); return; } submit.mutate({ eventId: Number(selectedEvent), teamId: team.id, title: submissionTitle.trim(), summary: submissionSummary.trim(), repositoryUrl: repo.trim(), demoUrl: demoUrl.trim() }); }} className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Event and team"><select value={selectedEvent} onChange={e => setSelectedEvent(e.target.value)}><option value="">Select a team event</option>{teams.map(team => <option key={team.id} value={team.eventId}>{events.find(event => event.id === team.eventId)?.title || `Event #${team.eventId}`} · {team.name}</option>)}</select></Field><Field label="Project title"><input value={submissionTitle} onChange={e => setSubmissionTitle(e.target.value)} placeholder="What are you building?" maxLength={220} required /></Field><Field label="Repository URL"><input value={repo} onChange={e => setRepo(e.target.value)} type="url" placeholder="https://github.com/team/project" /></Field><Field label="Demo URL"><input value={demoUrl} onChange={e => setDemoUrl(e.target.value)} type="url" placeholder="https://your-demo.example" /></Field><Field label="Project summary" wide><textarea rows={3} value={submissionSummary} onChange={e => setSubmissionSummary(e.target.value)} placeholder="What problem does it address, and how does it work?" minLength={20} maxLength={5000} required /></Field><div className="sm:col-span-2"><Button disabled={submit.isPending || !teams.length} className="rounded-xl bg-[#2926a6]">{submit.isPending ? "Submitting…" : "Submit project"}<ArrowRight className="ml-2 h-4 w-4" /></Button></div></form>
        {(submissionQuery.data ?? []).length > 0 && <div className="mt-5 space-y-2">{submissionQuery.data?.map(item => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#ededf4] dark:border-[#35354f] px-4 py-3"><div><p className="text-sm font-bold text-[#3b3c57]">{item.title}</p><p className="mt-1 text-[11px] text-[#85869a] dark:text-[#8888a3]">Version {item.version} · {new Date(item.submittedAt).toLocaleString()}</p></div><span className="rounded-full bg-[#edf7f1] px-2.5 py-1 text-[10px] font-bold capitalize text-[#32805f]">{item.status}</span></div>)}</div>}
      </section>
    </div>
    <aside className="space-y-4"><StatCard icon={ClipboardList} title="Registrations" value={registrationQuery.data?.length ?? 0} note="Active event registrations" /><StatCard icon={UsersRound} title="Teams" value={teams.length} note="Teams you belong to" /><StatCard icon={Award} title="Achievements" value={certificateQuery.data?.length ?? 0} note="Certificates issued to you" />
      <div className="rounded-[20px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5"><h3 className="text-sm font-bold text-[#3b3c57]">Registered events</h3>{registrationQuery.isLoading ? <p className="mt-3 text-xs text-[#8c8d9e]">Loading…</p> : (registrationQuery.data ?? []).length ? <div className="mt-3 space-y-3">{registrationQuery.data?.map(reg => <div key={reg.id} className="border-b border-[#f1f1f5] dark:border-[#292943] pb-3 last:border-0"><p className="text-xs font-bold text-[#484967]">{reg.event.title}</p><p className="mt-1 text-[10px] text-[#8c8d9e]">Registered {new Date(reg.createdAt).toLocaleDateString()}</p></div>)}</div> : <p className="mt-2 text-xs leading-5 text-[#898a9d] dark:text-[#8888a3]">Your registrations will show here. <a className="font-bold text-[#4844bb]" href="/events">Find an event</a>.</p>}</div>
      <div className="rounded-[20px] border border-[#e8e7f4] bg-[#f1f0ff] dark:bg-[#2c2b53] p-5"><p className="text-xs font-bold text-[#49468f] dark:text-[#cbc9ff]">Certificates</p>{(certificateQuery.data ?? []).length ? <div className="mt-3 space-y-3">{certificateQuery.data?.map(certificate => <div key={certificate.id} className="rounded-xl bg-white dark:bg-[#1e1e36] p-3"><p className="text-xs font-bold text-[#464760]">{certificate.achievement}</p><p className="mt-1 text-[10px] text-[#84859a]">{certificate.event.title} · {certificate.code}</p><a className="mt-2 inline-block text-[10px] font-bold text-[#4541b5] dark:text-[#8e8aff] underline underline-offset-2" href={`/certificates/${certificate.code}`}>View / print certificate →</a></div>)}</div> : <p className="mt-2 text-xs leading-5 text-[#7777a0] dark:text-[#74758d]">Completed achievements will be added to your profile when an organizer issues a certificate.</p>}</div>
    </aside></div></div>;
}

function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={`block text-xs font-bold text-[#4d4e68] ${wide ? "sm:col-span-2" : ""}`}>{label}<div className="mt-1.5 [&>input]:h-10 [&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#e6e6ef] dark:border-[#35354f] [&>input]:bg-[#fcfcfe] [&>input]:px-3 [&>input]:text-xs [&>input]:font-medium [&>input]:outline-none [&>input]:focus:border-[#aaa6ee] [&>textarea]:w-full [&>textarea]:rounded-lg [&>textarea]:border [&>textarea]:border-[#e6e6ef] dark:border-[#35354f] [&>textarea]:bg-[#fcfcfe] [&>textarea]:p-3 [&>textarea]:text-xs [&>textarea]:font-medium [&>textarea]:outline-none [&>textarea]:focus:border-[#aaa6ee] [&>select]:h-10 [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-[#e6e6ef] dark:border-[#35354f] [&>select]:bg-[#fcfcfe] [&>select]:px-3 [&>select]:text-xs">{children}</div></label>; }
function SectionTitle({ icon: Icon, title, subtitle }: { icon: typeof UsersRound; title: string; subtitle: string }) { return <div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f0efff] dark:bg-[#2c2b53] text-[#5550ca]"><Icon className="h-5 w-5" /></span><div><h2 className="font-display text-lg font-extrabold tracking-[-.03em] text-[#2b2c49] dark:text-[#f1f1fa]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#818297]">{subtitle}</p></div></div>; }
function StatCard({ icon: Icon, title, value, note }: { icon: typeof Award; title: string; value: number; note: string }) { return <div className="rounded-[20px] border border-[#e8e8f1] dark:border-[#35354f] bg-white dark:bg-[#1e1e36] p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#62637d]">{title}</span><Icon className="h-4 w-4 text-[#7975d9]" /></div><p className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] text-[#292a47] dark:text-[#f1f1fa]">{value}</p><p className="mt-1 text-[10px] text-[#9293a4]">{note}</p></div>; }
